# Generated by Django 5.2.8 on 2025-11-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50, verbose_name='Video file name')),
                ('path', models.CharField(max_length=500, verbose_name='Video File Path')),
                ('camera_name', models.CharField(max_length=255, verbose_name='Camera Name')),
                ('created_date', models.DateField(verbose_name='Date')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
