# Generated by Django 5.2.8 on 2025-11-14 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 17, 16, 41, 708254, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
