# Generated by Django 5.2.8 on 2025-11-14 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_video_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 14, 17, 17, 50, 484727, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
